"use client";
import { createContext, useContext, useState, useCallback } from 'react';

const LanguageContext = createContext({
  lang: 'en',
  setLang: () => {},
  toggleLanguage: () => {},
  t: (key) => key,
});
export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    hero: {
      badge: 'Premium Domain Marketplace',
      title1: 'Acquire Premium',
      titleHighlight: 'Aged Domains',
      title2: 'for SEO Success',
      subtitle: 'Discover high-authority aged domains with established backlinks, traffic, and domain ratings. Your shortcut to SEO dominance.',
      cta: 'Browse Domains',
      ctaSecondary: 'Learn More',
      stats: {
        domains: 'Domains Listed',
        rating: 'Avg. DR Score',
        customers: 'Happy Customers',
      },
    },
    benefits: {
      badge: 'Why Choose Us',
      title: 'The Advantages of ',
      titleHighlight: 'Aged Domains',
      subtitle: 'Premium aged domains give you an unfair advantage in SEO rankings and online authority.',
      items: [
        { title: 'Authority Backlinks', desc: 'Inherit high-quality backlinks from established domains' },
        { title: 'Faster Ranking', desc: 'Skip the sandbox period and rank faster on search engines' },
        { title: 'Established History', desc: 'Benefit from years of domain age and trust signals' },
        { title: 'SEO Ready', desc: 'Pre-vetted domains ready for immediate SEO campaigns' },
      ],
    },
    featured: {
      title: 'Featured Domains',
      subtitle: 'Handpicked premium domains with exceptional metrics and authority scores.',
      headers: { domain: 'Domain', dr: 'DR', da: 'DA', backlinks: 'Backlinks', traffic: 'Traffic', age: 'Age', price: 'Price', action: 'Action' },
      view: 'View',
      viewAll: 'View All Domains',
      yrs: 'yrs',
    },
    howItWorks: {
      badge: 'Simple Process',
      title: 'How It ',
      titleHighlight: 'Works',
      subtitle: 'Getting your premium domain is simple and straightforward.',
      steps: [
        { title: 'Browse Domains', desc: 'Explore our curated collection of premium aged domains' },
        { title: 'Contact Us', desc: 'Reach out for detailed metrics and pricing information' },
        { title: 'Secure Payment', desc: 'Complete your purchase through our secure payment system' },
        { title: 'Fast Transfer', desc: 'Receive your domain within 24-48 hours' },
      ],
    },
    faq: {
      title: 'Frequently Asked Questions',
      items: [
        { q: 'What is an aged domain?', a: 'An aged domain is a domain name that was registered years ago and has built up authority, backlinks, and trust signals over time. These domains are valuable for SEO because search engines tend to trust older domains more.' },
        { q: 'How do you verify domain metrics?', a: 'We use industry-standard tools like Ahrefs and Moz to verify Domain Rating (DR), Domain Authority (DA), backlink profiles, organic traffic, and spam scores for every domain in our marketplace.' },
        { q: 'Is the transfer process safe?', a: 'Yes, absolutely. We use established domain registrar transfer processes and provide guidance throughout. All transfers are backed by our guarantee.' },
        { q: 'Can I negotiate the price?', a: 'Yes, we are open to reasonable negotiations for most domains. Contact us with your offer and we will do our best to work with you.' },
        { q: 'How long does the transfer take?', a: 'Most domain transfers are completed within 5-7 business days. Some transfers may take up to 14 days depending on the registrar.' },
      ],
    },
    footer: {
      tagline: 'Your trusted source for premium aged domains. Boost your SEO with established domain authority.',
      quickLinks: 'Quick Links',
      browseDomains: 'Browse Domains',
      blog: 'Blog',
      aboutUs: 'About Us',
      contactLink: 'Contact',
      faqLink: 'FAQ',
      legal: 'Legal',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      refund: 'Refund Policy',
      copyright: 'All rights reserved.',
      resources: 'Resources',
      blogLink: 'Blog & Articles',
      seoGuides: 'SEO Guides',
      domainTools: 'Domain Tools',
      newsletter: 'Newsletter',
    },
    domains: {
      badge: 'Premium Domain Marketplace',
      title: 'Browse Domains',
      titleHighlight: 'Premium',
      subtitle: 'Explore our curated collection of premium aged domains with verified metrics.',
      search: 'Search domains...',
      filters: 'Filters',
      clearFilters: 'Clear Filters',
      priceRange: 'Price Range',
      drRange: 'DR Range',
      daRange: 'DA Range',
      ageRange: 'Age Range',
      sortBy: 'Sort By',
      ascending: 'Ascending',
      descending: 'Descending',
      min: 'Min',
      max: 'Max',
      noResults: 'No domains found matching your criteria.',
      adjustFilters: 'Try adjusting your filters or search terms.',
      showing: 'Showing',
      of: 'of',
      results: 'results',
      available: 'Available',
      sold: 'Sold',
    },
    domainDetail: {
      backToList: 'Back to Domains',
      metrics: 'Domain Metrics',
      domainRating: 'Domain Rating',
      domainAuthority: 'Domain Authority',
      pageAuthority: 'Page Authority',
      backlinks: 'Backlinks',
      traffic: 'Monthly Traffic',
      age: 'Domain Age',
      years: 'years',
      spamScore: 'Spam Score',
      indexed: 'Indexed',
      status: 'Status',
      language: 'Language',
      tld: 'TLD',
      registrar: 'Registrar',
      buyNow: 'Buy Now',
      addToWishlist: 'Add to Wishlist',
      savedToWishlist: 'Saved to Wishlist',
      contactUs: 'Contact Us',
      domainSold: 'This domain has been sold.',
      browseOther: 'Browse Other Domains',
      description: 'Description',
      additionalInfo: 'Additional Information',
    },
    wishlistPage: {
      badge: 'My Wishlist',
      title: 'Your Saved',
      titleHighlight: 'Domains',
      subtitle: 'You have {count} domain{s} saved',
      emptySubtitle: 'Your wishlist is empty. Start browsing and save domains you love!',
      emptyTitle: 'No domains saved yet',
      emptyDesc: 'Browse our marketplace and click the heart icon on any domain to add it to your wishlist.',
      browseDomains: 'Browse Domains',
      saved: 'Saved',
      actions: 'Actions',
    },
    blog: {
      badge: 'Blog & Resources',
      title: 'Latest Articles',
      subtitle: 'Tips, insights, and guides about domain investing and SEO.',
      readMore: 'Read More',
      latestPosts: 'Latest Posts',
      categories: 'Categories',
      tags: 'Tags',
      allCategories: 'All Categories',
      noPosts: 'No blog posts found.',
      backToBlog: 'Back to Blog',
      sectionBadge: 'Latest Articles',
      sectionTitle1: 'SEO Tips & ',
      sectionTitle2: 'Domain Insights',
      sectionSubtitle: 'Learn the latest strategies for leveraging aged domains to boost your SEO performance',
      viewAll: 'View All Articles',
      noBlogYet: 'No blog posts yet. Check back soon!',
    },
    nav: {
      home: 'Home',
      domains: 'Domains',
      blog: 'Blog',
      contact: 'Contact',
      viewDomains: 'View Domains',
      wishlist: 'Wishlist',
      benefits: 'Benefits',
      about: 'About',
    },
    about: {
      title: 'About Agedify',
      badge: 'About Agedify',
      heading1: 'Your Trusted Partner for ',
      heading2: 'Premium Domains',
      description: 'Agedify is a leading marketplace specializing in premium aged and expired domains. We curate only the highest quality domains with proven SEO metrics and clean histories.',
      points: ['Quality Checked Domains', 'Global SEO Use Cases', 'Fast & Secure Transfers', '24/7 Support'],
      domainsSold: 'Domains Sold',
      guarantee: 'Safe Transfer Guarantee',
      guaranteeDesc: 'Every domain transfer is protected with our comprehensive guarantee. We ensure secure and smooth transfers every time.',
    },
    contactForm: {
      title: 'Get in Touch',
      subtitle: 'Have questions about a domain or need assistance? Our team is here to help you find the perfect domain for your project.',
      badge: 'Contact Us',
      heading: 'Get In Touch',
      name: 'Name',
      email: 'Email',
      message: 'Message',
      namePlaceholder: 'Your name',
      emailPlaceholder: 'your@email.com',
      messagePlaceholder: 'Tell us about your domain needs...',
      submit: 'Send Message',
      sending: 'Sending...',
      success: 'Message sent successfully!',
      emailLabel: 'Email',
      phoneLabel: 'Phone',
      locationLabel: 'Location',
      locationValue: 'Global Service',
      info: {
        email: 'Email Us',
        phone: 'Call Us',
        location: 'Visit Us',
      },
    },
  },
  id: {
    hero: {
      badge: 'Marketplace Domain Premium',
      title1: 'Dapatkan Domain',
      titleHighlight: 'Aged Premium',
      title2: 'untuk Sukses SEO',
      subtitle: 'Temukan domain aged berautoritas tinggi dengan backlink, trafik, dan rating domain yang sudah mapan. Jalan pintas menuju dominasi SEO.',
      cta: 'Jelajahi Domain',
      ctaSecondary: 'Pelajari Lebih',
      stats: {
        domains: 'Domain Terdaftar',
        rating: 'Rata-rata DR',
        customers: 'Pelanggan Puas',
      },
    },
    benefits: {
      badge: 'Mengapa Memilih Kami',
      title: 'Keunggulan ',
      titleHighlight: 'Domain Aged',
      subtitle: 'Domain aged premium memberi keuntungan di peringkat SEO dan otoritas online.',
      items: [
        { title: 'Backlink Berkualitas', desc: 'Warisi backlink berkualitas tinggi dari domain yang sudah mapan' },
        { title: 'Ranking Lebih Cepat', desc: 'Lewati masa sandbox dan ranking lebih cepat di mesin pencari' },
        { title: 'Riwayat Mapan', desc: 'Manfaatkan tahun-tahun usia domain dan sinyal kepercayaan' },
        { title: 'Siap SEO', desc: 'Domain terverifikasi siap untuk kampanye SEO langsung' },
      ],
    },
    featured: {
      title: 'Domain Unggulan',
      subtitle: 'Domain premium pilihan dengan metrik dan skor otoritas yang luar biasa.',
      headers: { domain: 'Domain', dr: 'DR', da: 'DA', backlinks: 'Backlink', traffic: 'Trafik', age: 'Umur', price: 'Harga', action: 'Aksi' },
      view: 'Lihat',
      viewAll: 'Lihat Semua Domain',
      yrs: 'thn',
    },
    howItWorks: {
      badge: 'Proses Sederhana',
      title: 'Cara ',
      titleHighlight: 'Kerjanya',
      subtitle: 'Mendapatkan domain premium Anda sangat mudah dan sederhana.',
      steps: [
        { title: 'Jelajahi Domain', desc: 'Telusuri koleksi domain aged premium kami yang dikurasi' },
        { title: 'Hubungi Kami', desc: 'Tanyakan metrik detail dan informasi harga' },
        { title: 'Pembayaran Aman', desc: 'Selesaikan pembelian melalui sistem pembayaran aman kami' },
        { title: 'Transfer Cepat', desc: 'Terima domain Anda dalam 24-48 jam' },
      ],
    },
    faq: {
      title: 'Pertanyaan yang Sering Diajukan',
      items: [
        { q: 'Apa itu domain aged?', a: 'Domain aged adalah nama domain yang didaftarkan bertahun-tahun lalu dan telah membangun otoritas, backlink, dan sinyal kepercayaan dari waktu ke waktu. Domain ini berharga untuk SEO karena mesin pencari cenderung lebih mempercayai domain lama.' },
        { q: 'Bagaimana Anda memverifikasi metrik domain?', a: 'Kami menggunakan alat standar industri seperti Ahrefs dan Moz untuk memverifikasi Domain Rating (DR), Domain Authority (DA), profil backlink, trafik organik, dan skor spam untuk setiap domain di marketplace kami.' },
        { q: 'Apakah proses transfer aman?', a: 'Ya, tentu saja. Kami menggunakan proses transfer registrar domain yang sudah mapan dan memberikan panduan sepanjang proses. Semua transfer didukung oleh jaminan kami.' },
        { q: 'Bisakah saya negosiasi harga?', a: 'Ya, kami terbuka untuk negosiasi yang wajar untuk sebagian besar domain. Hubungi kami dengan penawaran Anda dan kami akan berusaha sebaik mungkin.' },
        { q: 'Berapa lama proses transfer?', a: 'Sebagian besar transfer domain selesai dalam 5-7 hari kerja. Beberapa transfer mungkin membutuhkan hingga 14 hari tergantung registrar.' },
      ],
    },
    contactForm: {
      title: 'Hubungi Kami',
      subtitle: 'Punya pertanyaan tentang domain atau butuh bantuan? Tim kami siap membantu.',
      badge: 'Hubungi Kami',
      heading: 'Hubungi Kami',
      name: 'Nama',
      email: 'Email',
      message: 'Pesan',
      namePlaceholder: 'Nama Anda',
      emailPlaceholder: 'email@anda.com',
      messagePlaceholder: 'Ceritakan kebutuhan domain Anda...',
      submit: 'Kirim Pesan',
      sending: 'Mengirim...',
      success: 'Pesan berhasil dikirim!',
      emailLabel: 'Email',
      phoneLabel: 'Telepon',
      locationLabel: 'Lokasi',
      locationValue: 'Layanan Global',
      info: {
        email: 'Email Kami',
        phone: 'Hubungi Kami',
        location: 'Kunjungi Kami',
      },
    },
    footer: {
      tagline: 'Sumber terpercaya Anda untuk domain aged premium. Tingkatkan SEO Anda dengan otoritas domain yang mapan.',
      quickLinks: 'Tautan Cepat',
      browseDomains: 'Jelajahi Domain',
      blog: 'Blog',
      aboutUs: 'Tentang Kami',
      contactLink: 'Kontak',
      faqLink: 'FAQ',
      legal: 'Legal',
      privacy: 'Kebijakan Privasi',
      terms: 'Syarat & Ketentuan',
      refund: 'Kebijakan Pengembalian',
      copyright: 'Hak cipta dilindungi.',
      resources: 'Sumber Daya',
      blogLink: 'Blog & Artikel',
      seoGuides: 'Panduan SEO',
      domainTools: 'Alat Domain',
      newsletter: 'Buletin',
    },
    domains: {
      badge: 'Marketplace Domain Premium',
      title: 'Jelajahi Domain',
      titleHighlight: 'Premium',
      subtitle: 'Telusuri koleksi domain aged premium kami yang dikurasi dengan metrik terverifikasi.',
      search: 'Cari domain...',
      filters: 'Filter',
      clearFilters: 'Hapus Filter',
      priceRange: 'Rentang Harga',
      drRange: 'Rentang DR',
      daRange: 'Rentang DA',
      ageRange: 'Rentang Umur',
      sortBy: 'Urutkan',
      ascending: 'Naik',
      descending: 'Turun',
      min: 'Min',
      max: 'Maks',
      noResults: 'Tidak ada domain yang cocok dengan kriteria Anda.',
      adjustFilters: 'Coba sesuaikan filter atau kata pencarian Anda.',
      showing: 'Menampilkan',
      of: 'dari',
      results: 'hasil',
      available: 'Tersedia',
      sold: 'Terjual',
    },
    domainDetail: {
      backToList: 'Kembali ke Domain',
      metrics: 'Metrik Domain',
      domainRating: 'Domain Rating',
      domainAuthority: 'Domain Authority',
      pageAuthority: 'Page Authority',
      backlinks: 'Backlink',
      traffic: 'Trafik Bulanan',
      age: 'Umur Domain',
      years: 'tahun',
      spamScore: 'Skor Spam',
      indexed: 'Terindeks',
      status: 'Status',
      language: 'Bahasa',
      tld: 'TLD',
      registrar: 'Registrar',
      buyNow: 'Beli Sekarang',
      addToWishlist: 'Tambah ke Favorit',
      savedToWishlist: 'Tersimpan di Favorit',
      contactUs: 'Hubungi Kami',
      domainSold: 'Domain ini sudah terjual.',
      browseOther: 'Jelajahi Domain Lain',
      description: 'Deskripsi',
      additionalInfo: 'Informasi Tambahan',
    },
    wishlistPage: {
      badge: 'Favorit Saya',
      title: 'Domain',
      titleHighlight: 'Tersimpan',
      subtitle: 'Anda memiliki {count} domain tersimpan',
      emptySubtitle: 'Daftar favorit Anda kosong. Mulai jelajahi dan simpan domain yang Anda sukai!',
      emptyTitle: 'Belum ada domain tersimpan',
      emptyDesc: 'Jelajahi marketplace kami dan klik ikon hati pada domain mana pun untuk menambahkannya ke favorit.',
      browseDomains: 'Jelajahi Domain',
      saved: 'Disimpan',
      actions: 'Aksi',
    },
    blog: {
      badge: 'Blog & Sumber Daya',
      title: 'Artikel Terbaru',
      subtitle: 'Tips, wawasan, dan panduan tentang investasi domain dan SEO.',
      readMore: 'Baca Selengkapnya',
      latestPosts: 'Artikel Terbaru',
      categories: 'Kategori',
      tags: 'Tag',
      allCategories: 'Semua Kategori',
      noPosts: 'Tidak ada artikel blog ditemukan.',
      backToBlog: 'Kembali ke Blog',
      sectionBadge: 'Artikel Terbaru',
      sectionTitle1: 'Tips SEO & ',
      sectionTitle2: 'Wawasan Domain',
      sectionSubtitle: 'Pelajari strategi terbaru untuk memanfaatkan domain aged guna meningkatkan performa SEO Anda',
      viewAll: 'Lihat Semua Artikel',
      noBlogYet: 'Belum ada artikel blog. Segera hadir!',
    },
    nav: {
      home: 'Beranda',
      domains: 'Domain',
      blog: 'Blog',
      contact: 'Kontak',
      viewDomains: 'Lihat Domain',
      wishlist: 'Favorit',
      benefits: 'Keunggulan',
      about: 'Tentang',
    },
    about: {
      title: 'Tentang Agedify',
      badge: 'Tentang Agedify',
      heading1: 'Partner Terpercaya untuk ',
      heading2: 'Domain Premium',
      description: 'Agedify adalah marketplace terkemuka yang mengkhususkan diri pada domain aged dan expired premium. Kami mengkurasi hanya domain berkualitas tertinggi dengan metrik SEO terbukti dan riwayat bersih.',
      points: ['Domain Terverifikasi', 'Untuk SEO Global', 'Transfer Cepat & Aman', 'Dukungan 24/7'],
      domainsSold: 'Domain Terjual',
      guarantee: 'Jaminan Transfer Aman',
      guaranteeDesc: 'Setiap transfer domain dilindungi dengan jaminan komprehensif kami. Kami memastikan transfer yang aman dan lancar.',
    },
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    if (typeof window === 'undefined') return 'en';
    return localStorage.getItem('agedify_lang') || 'en';
  });

  const toggleLanguage = useCallback(() => {
    setLang(prev => {
      const next = prev === 'en' ? 'id' : 'en';
      if (typeof window !== 'undefined') localStorage.setItem('agedify_lang', next);
      return next;
    });
  }, []);

  const setLanguage = useCallback((l) => {
    setLang(l);
    if (typeof window !== 'undefined') localStorage.setItem('agedify_lang', l);
  }, []);

  const t = useCallback((key) => {
    const keys = key.split('.');
    let val = translations[lang];
    for (const k of keys) {
      if (val === undefined) return key;
      val = val[k];
    }
    return val ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang: setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
